### ISSUE TITLE
Unicode string, different length in same lua code

### ISSUE THREAD

**Issue by BalazsNyiro** [rvirding/luerl#109]
In  tests for lib_string_format  pull request, in test/luerl_lib_string_format_SUITE.erl file,
in unicode_why_string_length_different_eval_vs_dofile(Config)  we realised an exciting behaviour of Luerl:

same string with special characters give back different string length from same lua code, depend on calling environment:
from erlang shell it gives back 22 as string length, from  .lua file it returns with 31.

Can you tell me why the string lengths are different?

**Comment by rvirding** [comment]
Which types of strings are you working with in erlang, list strings or binary strings? In Lua all strings are binaries without any special encoding, just one bytes and "normal" characters are one byte. Special characters or unicode then they will be UTF-8 encoded which means some characters will use more then one byte. But from the *Lua* point of view strings are just bytes, therefore there will be more of them.
In erlang list strings each character is one element of the list *irrespective* of what type of character they are.
Could you send show me some examples of where the length differs?

**Comment by BalazsNyiro** [comment]
Hi, here:
https://github.com/BalazsNyiro/luerl/blob/develop/test/luerl_lib_string_format_SUITE.erl
on the bottom of the erl file in unicode_why_string_length_different_eval_vs_dofile() function is an example:
{ok, [TxtLenEval]} = luerl:eval(<<"return string.len('árvíztűrő tükörfúrógép')">>),

This length is 22.

**Comment by rvirding** [comment]
OK, a simple answer to this issue is that it is due to the scanning.

When I scan in Luerl/erlang I get a sequence of bytes, one for each character, and it the bytes which are inserted into the string. There are 22 characters in the input string so there will be 22 bytes in the Luerl string. This also means that if I put a big unicode character (> 256) in the string then only the lowest byte will be included.

However, when scanning/parsing in Lua it will read unicoded characters directly as a sequence of UTF-8 encoded characters. Hence there are more bytes. I don't know when this was added to Lua as there is no direct mention of it in the manual. There strings are bytes and you can add UTF-8 encoded characters explicitly by using \u{XXX}.

I will have to think about to get the same handling in Luerl.

**Comment by rvirding** [comment]
A simple work around when entering commands is to use binaries as input and add a 'utf8' type to the binary:

    luerl:eval(<<"return string.len('árvíztűrő tükörfúrógép')"/utf8>>).

Yes, it's a hack. For files I don't know yet.

**Comment by rvirding** [comment]
I am continuing this discussion in https://github.com/rvirding/luerl/pull/118.
