### ISSUE TITLE
Persistent data structures 

### ISSUE THREAD

**Issue by ShalokShalom** [rvirding/luerl#115]
Hi there :)

Does Luerl provide persistent data structures?

I see this as a main disadvantage in Lua/Moonscript, which I like to use as a functional language.

Is there any way to use Lua as an immutable language (thanks to luerl)?

Thanks :D

**Comment by jchassoul** [comment]
HI (=

Luerl is an implementation of Lua 5.3 where instead of a C API we have Erlang at the lowest level, this means we can sandbox and script with the full power of the Lua language at the same time that we benefit from Erlang and all it features like immutable data and the powerful BEAM VM.

Is common in Luerl projects to use and deal with both Erlang and Lua and the same "eye of the needle approach" and "mechanisms not policies" we have in Lua apply here the big difference is that Luerl processes live inside the BEAM VM and not in the OS and interact with an Erlang API instead of C, apart from that is made to be compatible with standard Lua 5.3.

**Comment by ShalokShalom** [comment]
This does not solve my question, really. 

You write: `you benefit from Erlang and all it features like immutable data `

which sounds like I can use persistent data structures in luerl

**Comment by ShalokShalom** [comment]
So, we could implement persistent data structures of which all could benefit?

**Comment by ShalokShalom** [comment]
Yeah, a friend told me yesterday we can implement persistent data structures in luerl

**Comment by ShalokShalom** [comment]
Could this work?

https://github.com/PaulBernier/castl
https://www.npmjs.com/package/persistent

**Comment by rvirding** [comment]
Couldn't guarantee that Luerl could efficiently handle everything generated by `castl`. There are a few things Luerl doesn't handle yet: `_ENV` and `goto` and labels. Well you can define a label but you can't goto it.

So far no one has complained about the lack of these so they are not really in the pipeline, not the goto anyway.

Anyway as @jchassoul has pointed out from within Luerl all its data behaves in the same share/global/mutable way so you can't really get immutable data from the Lua inside Luerl. There is no support for that in Lua so it would be really strange.

Luerl has `userdata` in a similar way to Lua which allows you to pass Erlang data around inside Luerl but there is no way you can directly access it from Lua. Again the same as in standard Lua. So for example you could write a module in Erlang which you could call from Lua to send/receive messages and keep pids in the userdata. Or you could write a module which internally uses Erlang maps and access it from Lua. Note that these modules must be written in Erlang to be able to access Erlang.

Note that Lua can only directly handle Erlang data if it is in the forms it recognises.

**Comment by ShalokShalom** [comment]
Thanks a lot for these comments, I really appreciate it. :heart: :hugs: 

So far as I understand is the core reasoning that Luerl has no immutability simply because Lua has not?  

I can see your point, while you could say also that Lua has none of the properties that Erlang has so Luerl as a whole could be considered so strange as you find that idea.  

I think there is a solid idea behind this project and I am fully aware of the implications so that this addition would compile fine for Luerl and not for Lua or any other implementation, for that matter. 

I just think this is worth it.

**Comment by rvirding** [comment]
Luerl started out as implementation of a language with shared, global and mutable data as an experiment to see how this could be done. Lua was the language I chose and it kept growing till it finally became an implementation of Lua, at least as close as I could reasonably make it. Hence the handling of data is by design very Lua.

Also seeing you are running inside Erlang with and have a very close coupling I feel that if you wish to have that type of data handling you do it in Erlang. You can always implement a module in Erlang with a Lua interface which gives you that type of data.

**Comment by ShalokShalom** [comment]
Yes, this is exactly as I thought. Do you see it as beneficial for every user, to have this capacity?

**Comment by rvirding** [comment]
Depends how you define "have this capacity". It is the system builder who defines what users have access to. To be able to add modules which can extend how I can access Erlang data and the Erlang system I need to be able to access the system though the Erlang interface. So if I can **ONLY** write Lua code which is executed by the system then I can not do this.

This is what makes sandboxing relatively easy. When setting up the system you can quite simply remove certain tables, for example io and os, or functions. The when executing Lua these are just not available and can not be added. Check out the `luerl_sandbox.erl` module.

**Comment by ShalokShalom** [comment]
There seems to be a misunderstanding. 
My understanding is that this is something that can be implemented globally on a generic way. Is this correct?

**Comment by jchassoul** [comment]
No, there is no generic global things in the Erlang environment, we don't share memory, there is no global state even in Luerl you usually have more than one Lua process running and the way those interact between each other and the environment is not by reading a global state but by passing messages, that common pattern enable by the BEAM is also why you don't need Luerl coroutines since an Erlang process with is own Lua VM is much more powerful than that.

**Comment by rvirding** [comment]
Getting back to this really late!

What you could do is write a module which you call from Luerl which accesses data in an ETS table. This could then be shared with other Luerl processes and other things written in Erlang. While this is not shared, global or mutable it is about as close as you can get to that in the Erlang system.

**Comment by ShalokShalom** [comment]
God, was I inexperienced back then. 😄 Still, I found a library and thought I post it here, in case somebody stumbled over this issue. https://github.com/paweljarosz/lua-immutable
