### ISSUE TITLE
Lua coroutines in Luerl?

### ISSUE THREAD

**Issue by novabyte** [rvirding/luerl#62]
Would it be possible to implement coroutines support in Luerl? If so, can you give me some pointers on where I should start?

**Comment by rvirding** [comment]
It would definitely be possible to implement coroutines in Luerl. It is one of the things I have been considering to add to Luerl. However, I have not yet really tried to understand how coroutines actually work in Lua so I have not worked out how they should be added to Luerl. For example, can we add them "on top" of the existing system, or do they need to be at the base and the existing system be built on top of them? So it is very difficult for me to come with some pointers at the current time.

Can I ask if there is a specific reason why you want them and what in what time-frame we are looking at? The reason I am asking for in the next 3-4 weeks I will not have much time to look at this but I had planned to work on Luerl during the summer.

**Comment by novabyte** [comment]
> can we add them "on top" of the existing system, or do they need to be at the base and the existing system be built on top of them?

This is exactly the question I had hoped you'd be able to answer. 😃 

> Can I ask if there is a specific reason why you want them and what in what time-frame we are looking at?

Sure. We're just about to launch a second generation of our code execution service and would like to use `luerl`. The reasons include:

* Module/Function-based execution. We can pre-process the script and extract mappings for our execution API.
* Re-map `require` to work within our sand-boxed hosted code.
* Hosted Modules (so called "Cloud Modules")

The specific reason for coroutine support was just to enable us to provide an async/await style execution model within the Lua scripts which run requests to internal APIs in our service. I could easily build this model up with coroutine support.

Does this help? I'm happy to go into more detail if you prefer by email.

**Comment by rvirding** [comment]
I have checked and the current implementation cannot be directly used to implement coroutines. While some data is explicitly kept in a stack not everything is, specifically the actual function call-stack is not. While this is definitely possible to do it would require changes in many parts internally.

One reason I have not really looked at it is that when I have needed something like coroutines I have instead used Erlang's processes. I then run Luerl inside each process and use Erlang messages for communication and leave the scheduling to Erlang. This works very well but it is not quite the same thing and it does mean you can't just use already coroutine-based code must it must be specially written for this.

Another issue is that as all these "lua processes" are running in separate erlang processes they can't share any state.

I do have my space ships demo as an example of this. I have not really released the code but that is not because it is "secret" in any way but that it needs cleaning up before I make it public.
