### ISSUE TITLE
Execute function defined in a Lua "module"?

### ISSUE THREAD

**Issue by novabyte** [rvirding/luerl#63]
If I have a Lua script like so:

```lua
local Mod = {}
function Mod.foo()
    print("Test")
end
return Mod
```

And I run it within the Luerl VM like so:

```erlang
St0 = luerl:init(),
{Res, St1} = luerl:do(<<"Lua code above">>, St0),
erlang:display(Res)
```

I get back `[{:tref, 16}]` in my particular script (not quite the one above). I can see this is a table reference ID but how do I execute the `foo` function defined within the Lua script?

**Comment by novabyte** [comment]
I've looked at `luerl:call_function` but am unclear on how to provide the `Res` I get back from the script execution as the "context" to search and call the function within.

**Comment by novabyte** [comment]
I'm following the common approach to module definition in Lua - http://lua-users.org/wiki/ModuleDefinition

**Comment by rvirding** [comment]
Sitting by the sea, will get back to you this evening.

**Comment by novabyte** [comment]
@rvirding Hah. Have a great day with sunshine. 😃

**Comment by rvirding** [comment]
Yes, it is the standard way of defining modules and of course it works in luerl. The issue is that there is no function in `luerl` which directly supports that when calling from erlang. All the existing functions for calling functions and methods and accessing tables assume you have a "named path" down the tables from `_G`: `foo.bar.baz(1,2, 3)`. The sequence of calls you need to make is:

    {[M],St1} = luerl:dofile("xx.lua", St0),                  -- Load and call the chunk
    {F,St2} = luerl_emul:get_table_key(M, <<"foo">>, St1),
    luerl_emul:functioncall(F, [], St2)

To make it even more basic you can replace the first line with

    {ok,Mod,St1} = luerl:loadfile("xx.lua", St0),            -- Load the chunk
    {[M],St2} = luerl_emul:functioncall(Mod, [], St1),       -- Call the chunk

Doing `luerl:do` works of course.

I intend to revise and clean up the interface functions in `luerl` but that will probably come with Lua 5.3 as it will be backwards incompatible.

**Comment by novabyte** [comment]
@rvirding I've just tested my code with your example and it works perfectly. Let me know if you want some feedback or help with the changes for Lua 5.3. Thank you for your help.
