### ISSUE TITLE
erlang 20.1.1 isntall error

### ISSUE THREAD

**Issue by pampanelson** [rvirding/luerl#88]
For a step by step:
$ mkdir luerl_demo
$ cd luerl_demo
$ curl https://erlang.mk/erlang.mk -o erlang.mk
$ echo "DEPS = luerl\ninclude erlang.mk" > Makefile
$ make

but with error : 
init terminating in do_boot",{badarg,[{erlang,atom_to_list,["20.1.1"],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,469}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,470}]},{erl_eval,expr_list,6,[{file,"erl_eval.erl"},{line,878}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,422}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]}]}}
init terminating in do_boot ({badarg,[{erlang,atom_to_list,20.1.1,[]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,expr_list,6,[{_},{_}]},{erl_eval

Crash dump is being written to: erl_crash.dump...done

**Comment by pampanelson** [comment]
for otp 19 I got errors : 

{"init terminating in do_boot",{undef,[{rmemo,start,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,670}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,122}]},{init,start_it,1,[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
Error: No Makefile to build dependency /Users/pampa/loho/erlang/erlstart/luerl_demo/deps/luerl.
make: *** [erlang.mk:4239: deps] Error 2

**Comment by jchassoul** [comment]
Thanks for your report, I'm re-doing the getting started doc to remove this issue will back with the changes shortly, thanks again for your report!

**Comment by jchassoul** [comment]
I think this issue is related with the changes @Licenser and @rvirding needed for the new awesome luerl hex.pm package I notice the changes are currently breaking previous workflows like building luerl from erlang.mk, I also test updating the Makefile to fetch the library from hex directly using dep_luerl = hex 0.3.1 with the same error results at build time reported by this issue and  on the slack channel.

There is lots of value on have a working library that people can fetch from package managers and building systems like hex.pm and erlang.mk, instead of one solution indirectly cannibalizing the other I hope we can get this working on both environments.

**Comment by jchassoul** [comment]
After some updates now we can build again luerl hopefully both with hex.pm and erlang.mk @pampanelson please check again (=

**Comment by pampanelson** [comment]
you guys are wonderful!

glad to see this output:
Hello, Robert!
Hello, File!
Hello, Chunk!

ps: mac maybe need " brew install sdl2 sdl2_image " for running hello world demo

**Comment by jchassoul** [comment]
Thanks for all your help reporting this issue and testing you are awesome! 

glad you finally could run the code, If I recall this correctly you need to get sdl2 and sdl2_image like you mention I think they are separate for some random reason I promise you that the result it's going to be awesome, but I wonder if its beltter to remove that from the getting started just to avoid confusion.

What do you think? can't wait for some feedback. (=
